default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Chat-API_development
  #username: Chat-API
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #min_messages: notice


test:
  <<: *default
  database: Chat-API_test


production:
  <<: *default
  database: Chat-API_production
  username: Chat-API
  password: <%= ENV['CHAT-API_DATABASE_PASSWORD'] %>
